apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: my-aidecipher

images:
- name: leebs1986/my_aidecipher_server
  newName: leebs1986/my_aidecipher_server
  newTag: 809423e-dev

patchesStrategicMerge:
  - deployment-patch.yaml