apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-aidecipher-deployment
  labels:
    app: my-aidecipher-server
spec:
  selector:
    matchLabels:
      app: my-aidecipher-server
  template:
    metadata:
      name: my-aidecipher-pod
      labels:
        app: my-aidecipher-server
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: my-aidecipher-container
          image: leebs1986/my_aidecipher_server:809423e-dev
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
          command: ['/docker/entrypoint.sh']
          args:
            - gunicorn
            - --log-level=info
            #- --access-logfile=/var/log/gunicorn.log
            #- --keep-alive=5
          env:
            - name: PYTHONPATH
              value: '/src'
            - name: PYTHONUNBUFFERED
              value: '1'
            - name: PYTHONUTF8
              value: '1'
            - name: MY_STAGE
              value: 'dev'
            - name: MY_VERSION
              value: '1.0.0'
            #- name: MY_ROOT
            #  value:
            - name: MY_NAME
              value: 'API'
            - name: MY_LOCAL
              value: '1'
