apiVersion: v1
kind: Service
metadata:
  name: my-aidecipher-service
  labels:
    app: my-aidecipher-server
spec:
  type: ClusterIP
  selector:
    app: my-aidecipher-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
